feign:
  url:
    prefix: http://localhost:8080/target_server # FeignDemoClient 에서 사용할 url prefix 값
  client:
    config:
      default:
        connect-timeout: 1000 # 단위는 ms
        read-timeout: 3000 # 단위는 ms
        logger-level: NONE
      demo-client: # FeignDemoClient 에서 사용할 Client 에 따로 설정
        connect-timeout: 1000
        read-timeout: 10000
        logger-level: HEADERS # 여기서 설정한 값은 FeignCustomLogger -> Logger.Level logLevel 변수에 할당됨