# article 30 개 더미데이터
# article_comment 25 개 더미데이터
# defer-datasource-initialization: true
# sql.init.mode: always
insert into article (id, title, content, hashtag, create_at, modified_at, created_by, modified_by) values
                                                                                                       (1, 'title_01', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (2, 'title_02', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (3, 'title_03', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (4, 'title_04', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (5, 'title_05', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (6, 'title_06', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (7, 'title_07', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (8, 'title_08', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (9, 'title_09', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (10, 'title_10', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (11, 'title_11', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (12, 'title_12', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (13, 'title_13', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (14, 'title_14', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (15, 'title_15', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (16, 'title_16', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (17, 'title_17', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (18, 'title_18', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (19, 'title_19', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (20, 'title_20', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (21, 'title_21', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (22, 'title_22', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (23, 'title_23', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (24, 'title_24', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (25, 'title_25', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (26, 'title_26', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (27, 'title_27', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (28, 'title_28', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (29, 'title_29', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats'),
                                                                                                       (30, 'title_30', 'content_01', 'hashTag', now(), now(), 'hooneats', 'hooneats');

--
# insert into article_comment (id, content, article_id, create_at, modified_at, created_by, modified_by) values
#                                                                                                            (0,'content_01', 1, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_02', 2, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_03', 3, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_04', 4, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_05', 5, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_06', 6, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_07', 7, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_08', 8, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_09', 9, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_10', 10, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_11', 11, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_12', 12, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_13', 13, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_14', 14, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_15', 15, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_16', 16, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_17', 17, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_18', 18, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_19', 19, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_20', 20, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_21', 21, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_22', 22, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_23', 23, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_24', 24, now(), now(), 'hooneats', 'hooneats'),
#                                                                                                            (0,'content_26', 25, now(), now(), 'hooneats', 'hooneats');
#